name: last_mile
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_swiper: ^1.1.2
  flutter_staggered_grid_view: ^0.3.0
  rubber: ^0.3.2
  flutter_page_indicator: ^0.0.3
  pin_code_text_field: ^1.3.6
  country_code_picker: ^1.1.5
  http: any
  intl: any
  location: ^2.5.3
  flutter_calendar: ^0.0.9
  cupertino_range_slider: ^1.0.1
  flutter_range_slider: "^1.4.0"
  flutter_xlider: ^3.4.0
  numberpicker: ^1.0.0
  google_maps_flutter: ^0.5.20+2
  modal_bottom_sheet: ^0.1.6+1
  flare_splash_screen: ^2.1.2
  flutter_svg: ^0.14.0
  flutter_rating_bar: ^3.0.1+1
  solid_bottom_sheet: ^0.1.9
  calendarro: ^1.0.0
  universal_html: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:


  uses-material-design: true

  assets:
    - assets/
